import { createCipheriv, pbkdf2, randomBytes } from "node:crypto";
import type { AssetRecord, ServerProfileSummary } from "../shared/ipc";

const PBKDF2_ITERATIONS = 310_000;

function deriveKey(passphrase: string, salt: Buffer): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    pbkdf2(passphrase, salt, PBKDF2_ITERATIONS, 32, "sha256", (error, key) => {
      if (error) reject(error); else resolve(key);
    });
  });
}

export async function buildEncryptedRunbook(
  profiles: ServerProfileSummary[],
  assets: AssetRecord[],
  passphrase: string,
): Promise<string> {
  const generatedAt = new Date().toISOString();
  const groupedProfiles = new Map<string, ServerProfileSummary[]>();
  for (const profile of profiles) {
    const group = profile.group || "Ungrouped";
    groupedProfiles.set(group, [...(groupedProfiles.get(group) ?? []), profile]);
  }
  const topology = [...groupedProfiles.entries()]
    .map(([group, members]) => ({
      group,
      connections: members.map((profile) => ({
        id: profile.id,
        name: profile.name,
        host: profile.host,
        protocol: profile.protocol,
      })),
    }))
    .sort((left, right) => left.group.localeCompare(right.group));
  const payload = JSON.stringify({
    format: "CyberGrid Disaster Recovery Runbook",
    version: 1,
    generatedAt,
    topology,
    profiles: profiles.map((profile) => ({
      id: profile.id,
      name: profile.name,
      category: profile.category,
      group: profile.group,
      protocol: profile.protocol,
      host: profile.host,
      port: profile.port,
      username: profile.username,
      domain: profile.domain,
      tags: profile.tags,
      icon: profile.icon,
      applicationBadge: profile.applicationBadge,
      notes: profile.notes,
      configBackups: profile.configBackups,
    })),
    assets,
  });
  const salt = randomBytes(16);
  const iv = randomBytes(12);
  const key = await deriveKey(passphrase, salt);
  try {
    const cipher = createCipheriv("aes-256-gcm", key, iv);
    const encrypted = Buffer.concat([cipher.update(payload, "utf8"), cipher.final(), cipher.getAuthTag()]);
    const envelope = JSON.stringify({
      version: 1,
      kdf: "PBKDF2-SHA256",
      iterations: PBKDF2_ITERATIONS,
      salt: salt.toString("base64"),
      iv: iv.toString("base64"),
      ciphertext: encrypted.toString("base64"),
    }).replace(/</g, "\\u003c");
    return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CyberGrid Disaster Recovery Runbook</title><style>
:root{color-scheme:dark;font:14px system-ui,sans-serif;background:#080d14;color:#d7e2ef}*{box-sizing:border-box}body{margin:0}main{width:min(1100px,calc(100% - 32px));margin:32px auto}header{display:flex;gap:14px;align-items:center;margin-bottom:24px}.logo{display:grid;width:42px;height:42px;place-items:center;border:1px solid #23d5ab;border-radius:10px;color:#23d5ab;font-weight:900}h1,h2,h3{margin:.2em 0}p{color:#8fa1b6;line-height:1.55}.unlock{max-width:460px;padding:24px;border:1px solid #213044;border-radius:12px;background:#0d1520}input,button{height:40px;border:1px solid #213044;border-radius:7px;background:#09111a;color:#d7e2ef;padding:0 12px}input{width:100%;margin:12px 0}button{background:#23d5ab;color:#04120f;font-weight:800;cursor:pointer}.error{color:#ff7d89}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.card,section{padding:16px;border:1px solid #213044;border-radius:10px;background:#0d1520}.card strong{display:block;font-size:24px;color:#23d5ab}.grid{display:grid;gap:12px;margin:16px 0}.topology{grid-template-columns:repeat(auto-fit,minmax(240px,1fr))}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #213044;text-align:left;vertical-align:top}th{color:#8fa1b6;font-size:11px;text-transform:uppercase}details{margin:8px 0;border:1px solid #213044;border-radius:7px}summary{padding:10px;cursor:pointer;font-weight:750}pre{overflow:auto;margin:0;padding:12px;border-top:1px solid #213044;white-space:pre-wrap;font:12px ui-monospace,monospace}.muted{color:#8fa1b6}.hidden{display:none}
</style></head><body><main><header><div class="logo">CG</div><div><h1>Disaster Recovery Runbook</h1><p>Portable encrypted inventory generated by CyberGrid.</p></div></header>
<section class="unlock" id="unlock"><h2>Unlock offline runbook</h2><p>Enter the export passphrase. Decryption happens locally in this browser and no network connection is required.</p><form id="form"><input id="password" type="password" minlength="12" required autocomplete="current-password" placeholder="Runbook passphrase"><button>Decrypt runbook</button></form><p class="error" id="error"></p></section><div id="content" class="hidden"></div></main>
<script id="envelope" type="application/json">${envelope}</script><script>
const q=(s)=>document.querySelector(s), b64=(s)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
function render(data){const root=q('#content');root.replaceChildren();const summary=el('div',undefined,'summary');for(const [label,value] of [['Connections',data.profiles.length],['Assets',data.assets.length],['Generated',new Date(data.generatedAt).toLocaleString()]]){const card=el('div',undefined,'card');card.append(el('strong',String(value)),el('span',label,'muted'));summary.append(card)}root.append(summary);const topology=el('div',undefined,'grid topology');for(const group of data.topology){const card=el('section');card.append(el('h3',group.group));for(const connection of group.connections)card.append(el('p',connection.protocol.toUpperCase()+' · '+connection.name+' · '+connection.host));topology.append(card)}root.append(el('h2','Topology'),topology);const inventory=el('section');inventory.append(el('h2','Connection Inventory'));const table=el('table'),head=el('tr');for(const name of ['Name','Group','Protocol','Endpoint','Operator'])head.append(el('th',name));table.append(head);for(const profile of data.profiles){const row=el('tr');for(const value of [profile.name,profile.group,profile.protocol.toUpperCase(),profile.host+':'+profile.port,profile.username||'—'])row.append(el('td',value));table.append(row);if(profile.notes||profile.configBackups.length){const detailRow=el('tr'),cell=el('td');cell.colSpan=5;const details=el('details'),summaryLine=el('summary','Reference notes & config history');if(profile.notes)details.append(summaryLine,el('pre',profile.notes));else details.append(summaryLine);for(const backup of profile.configBackups){details.append(el('h3',backup.name),el('pre',backup.content))}cell.append(details);detailRow.append(cell);table.append(detailRow)}}inventory.append(table);root.append(inventory);const assets=el('section');assets.append(el('h2','Asset Inventory'));for(const asset of data.assets){const details=el('details'),summaryLine=el('summary',asset.name+' · '+asset.ipAddress+' · '+asset.osFamily),meta=el('pre',JSON.stringify({hostname:asset.hostname,macAddress:asset.macAddress,vendor:asset.vendor,metadata:asset.metadata,openPorts:asset.openPorts},null,2));details.append(summaryLine,meta);assets.append(details)}root.append(assets);q('#unlock').classList.add('hidden');root.classList.remove('hidden')}
q('#form').addEventListener('submit',async(e)=>{e.preventDefault();q('#error').textContent='';try{const box=JSON.parse(q('#envelope').textContent),pass=new TextEncoder().encode(q('#password').value),material=await crypto.subtle.importKey('raw',pass,'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b64(box.salt),iterations:box.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(box.iv)},key,b64(box.ciphertext));render(JSON.parse(new TextDecoder().decode(plain)))}catch{q('#error').textContent='Unable to decrypt. Check the passphrase and file integrity.'}});
</script></body></html>`;
  } finally {
    key.fill(0);
  }
}
